# Generated by Django 5.2 on 2025-05-09 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Home_Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('price_min', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price_max', models.DecimalField(decimal_places=2, max_digits=10)),
                ('category', models.CharField(default='Real Estate', max_length=100)),
                ('image_main', models.ImageField(blank=True, null=True, upload_to='Name')),
                ('image_person', models.ImageField(blank=True, null=True, upload_to='Name')),
                ('location', models.CharField(max_length=255)),
            ],
        ),
    ]
