# Generated by Django 5.2 on 2025-05-13 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0003_booking_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='home_property',
            name='price_min',
        ),
    ]
